services:
  dns-server:
    container_name: technitium-dns
    image: technitium/dns-server:latest

    ports:
      - "5380:5380/tcp" # Web UI
      - "127.0.0.1:53:53/udp"     # DNS UDP
      - "127.0.0.1:53:53/tcp"     # DNS TCP
    environment:
      - DNS_SERVER_DOMAIN=dns-server.local
      - TZ=Asia/Dhaka
    volumes:
      - ./config:/etc/dns
    restart: unless-stopped
